version: '3.9'

services:
  web:
    build: .
    container_name: thug_web
    command: ["/bin/bash", "/app/entrypoint.sh"]
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
