services:
  - type: web
    name: thug-cafe
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: thug-cafe-db
          property: connectionString

databases:
  - name: thug-cafe-db
    databaseName: thugcafe
    user: postgres
